- name: Setup Tomcat8 & Deploy Artifact
  hosts: tomcat
  become: yes
  vars:
    war_file: /opt/jenkins/workspace/VisOps/t055/sample-java-app/deploy-on-tomcat/hello-world/webapp/target/webapp.war 

  tasks:
    - name: Copy WAR file from Jenkins to Tomcat server
      copy:
        src: "{{ war_file }}"
        dest: /opt/tomcat10/webapps/ROOT.war

    - name: Stop tomcat service
      service:
        name: tomcat
        state: stopped

    - name: Delete existing ROOT directory
      file:
        path: /opt/tomcat10/webapps/ROOT
        state: absent

    - name: Start Tomcat service
      service:
        name: tomcat
        state: started
